services:
  - type: web
    name: anime-reviews-api
    env: node
    buildCommand: npm run build
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
